
CREATE LOGIN Melsy WITH PASSWORD = 'Password123', CHECK_POLICY = OFF;
ALTER LOGIN Melsy ENABLE;
ALTER LOGIN Melsy WITH PASSWORD = 'Password#123';
ALTER LOGIN Melsy ENABLE;


SELECT @@SERVERNAME;

ALTER LOGIN Melsy ENABLE;
ALTER LOGIN Melsy WITH PASSWORD = 'Password@123';

-- Set default database correctly
ALTER LOGIN Melsy WITH DEFAULT_DATABASE = HealthAxis3;


SELECT SERVERPROPERTY('IsIntegratedSecurityOnly');